# docker-compose up -d --force-recreate
version: "3.0"
services:
  deploy:
    image: registry-vpc.cn-shanghai.aliyuncs.com/louisehong/deploy:1.0.9
    restart: always
    volumes:
      - "/data/logs/gin:/logs"
      - "/app/:/app/"
    ports:
      - "8000:8000"
