# docker-compose up -d --force-recreate
version: "3.0"
services:
  deploy:
    image: louisehong/deploy:latest
    restart: always
    volumes:
      - "/data/logs/gin:/logs"
      - "/data/:/app/"
    ports:
      - "8000:8000"
